### ISSUE TITLE
Include a license for project

### ISSUE THREAD

**Issue by charliek** [hypereddie/HippyJava#1]
I was wondering what license the source for your project is under? I have tried this project out and have had success, but before incorporating the project I need to understand the licensing. 

Personally I prefer Apache, MIT, or BSD style licenses.

**Comment by ecp4224** [comment]
Oh wow, I can't believe I forgot about that :p
0ca85d0 adds the MIT license

**Comment by charliek** [comment]
Great. Thanks!
