### ISSUE TITLE
Publish an artifact, please.

### ISSUE THREAD

**Issue by Jacoby6000** [hypereddie/HippyJava#2]
I've been able to use this to create chatbots successfully. Please publish an artifact so I can more easily retrieve this as a dependency :)

**Comment by ecp4224** [comment]
I've made a jar release [here](https://github.com/hypereddie/HippyJava/releases/tag/v1.0)
I'll look into publishing it as a maven dependency this week, as I've never done so before..

**Comment by Daij-Djan** [comment]
this doesnt contain the hippy classes ;)

**Comment by ecp4224** [comment]
I've published a maven build and added install instructions to the README.

Closing this now
